[package]
name = "cng3"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
async-trait = "0.1.88"
chrono = "0.4.41"
log = "0.4.27"
ratatui = "0.29.0"
shell-words = "1.1.0"
tokio = { version = "1.45.1", features = ["full"] }
